/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ControlRouteRouteImport } from './routes/control/route'
import { Route as PendienteRouteImport } from './routes/pendiente'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedEquipoRouteImport } from './routes/_authenticated/equipo'
import { Route as AuthenticatedFinanzasRouteImport } from './routes/_authenticated/finanzas'
import { Route as AuthenticatedHuespedesRouteImport } from './routes/_authenticated/huespedes'
import { Route as AuthenticatedIntegracionesRouteImport } from './routes/_authenticated/integraciones'
import { Route as AuthenticatedMisTareasRouteImport } from './routes/_authenticated/mis-tareas'
import { Route as AuthenticatedOperacionesRouteImport } from './routes/_authenticated/operaciones'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedPropiedadesRouteImport } from './routes/_authenticated/propiedades'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'
import { Route as AuthenticatedTrabajoRouteRouteImport } from './routes/_authenticated/trabajo/route'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as ControlIndexRouteImport } from './routes/control/index'
import { Route as ControlDashboardRouteImport } from './routes/control/dashboard'
import { Route as ControlEmpresasRouteImport } from './routes/control/empresas'
import { Route as ControlLicenciasRouteImport } from './routes/control/licencias'
import { Route as ControlSistemaRouteImport } from './routes/control/sistema'
import { Route as ControlUsuariosRouteImport } from './routes/control/usuarios'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedTrabajoIndexRouteImport } from './routes/_authenticated/trabajo/index'
import { Route as AuthenticatedTrabajoCalendarioRouteImport } from './routes/_authenticated/trabajo/calendario'
import { Route as AuthenticatedTrabajoIncidenciasRouteImport } from './routes/_authenticated/trabajo/incidencias'
import { Route as AuthenticatedTrabajoPerfilRouteImport } from './routes/_authenticated/trabajo/perfil'
import { Route as AuthenticatedTrabajoTareasRouteImport } from './routes/_authenticated/trabajo/tareas'
import { Route as ApiPublicEmailAlertsRouteImport } from './routes/api/public/email-alerts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRouteRoute = ControlRouteRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const PendienteRoute = PendienteRouteImport.update({
  id: '/pendiente',
  path: '/pendiente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipoRoute = AuthenticatedEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanzasRoute = AuthenticatedFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHuespedesRoute = AuthenticatedHuespedesRouteImport.update({
  id: '/huespedes',
  path: '/huespedes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracionesRoute =
  AuthenticatedIntegracionesRouteImport.update({
    id: '/integraciones',
    path: '/integraciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMisTareasRoute = AuthenticatedMisTareasRouteImport.update({
  id: '/mis-tareas',
  path: '/mis-tareas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacionesRoute =
  AuthenticatedOperacionesRouteImport.update({
    id: '/operaciones',
    path: '/operaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropiedadesRoute =
  AuthenticatedPropiedadesRouteImport.update({
    id: '/propiedades',
    path: '/propiedades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrabajoRouteRoute =
  AuthenticatedTrabajoRouteRouteImport.update({
    id: '/trabajo',
    path: '/trabajo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ControlIndexRoute = ControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlRouteRoute,
} as any)
const ControlDashboardRoute = ControlDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ControlRouteRoute,
} as any)
const ControlEmpresasRoute = ControlEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => ControlRouteRoute,
} as any)
const ControlLicenciasRoute = ControlLicenciasRouteImport.update({
  id: '/licencias',
  path: '/licencias',
  getParentRoute: () => ControlRouteRoute,
} as any)
const ControlSistemaRoute = ControlSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => ControlRouteRoute,
} as any)
const ControlUsuariosRoute = ControlUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => ControlRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrabajoIndexRoute =
  AuthenticatedTrabajoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTrabajoRouteRoute,
  } as any)
const AuthenticatedTrabajoCalendarioRoute =
  AuthenticatedTrabajoCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedTrabajoRouteRoute,
  } as any)
const AuthenticatedTrabajoIncidenciasRoute =
  AuthenticatedTrabajoIncidenciasRouteImport.update({
    id: '/incidencias',
    path: '/incidencias',
    getParentRoute: () => AuthenticatedTrabajoRouteRoute,
  } as any)
const AuthenticatedTrabajoPerfilRoute =
  AuthenticatedTrabajoPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedTrabajoRouteRoute,
  } as any)
const AuthenticatedTrabajoTareasRoute =
  AuthenticatedTrabajoTareasRouteImport.update({
    id: '/tareas',
    path: '/tareas',
    getParentRoute: () => AuthenticatedTrabajoRouteRoute,
  } as any)
const ApiPublicEmailAlertsRoute = ApiPublicEmailAlertsRouteImport.update({
  id: '/api/public/email-alerts',
  path: '/api/public/email-alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control': typeof ControlRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pendiente': typeof PendienteRoute
  '/trabajo': typeof AuthenticatedTrabajoRouteRouteWithChildren
  '/alertas': typeof AuthenticatedAlertasRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/huespedes': typeof AuthenticatedHuespedesRoute
  '/integraciones': typeof AuthenticatedIntegracionesRoute
  '/mis-tareas': typeof AuthenticatedMisTareasRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/propiedades': typeof AuthenticatedPropiedadesRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/control/dashboard': typeof ControlDashboardRoute
  '/control/empresas': typeof ControlEmpresasRoute
  '/control/licencias': typeof ControlLicenciasRoute
  '/control/sistema': typeof ControlSistemaRoute
  '/control/usuarios': typeof ControlUsuariosRoute
  '/invite/$token': typeof InviteTokenRoute
  '/control/': typeof ControlIndexRoute
  '/trabajo/calendario': typeof AuthenticatedTrabajoCalendarioRoute
  '/trabajo/incidencias': typeof AuthenticatedTrabajoIncidenciasRoute
  '/trabajo/perfil': typeof AuthenticatedTrabajoPerfilRoute
  '/trabajo/tareas': typeof AuthenticatedTrabajoTareasRoute
  '/api/public/email-alerts': typeof ApiPublicEmailAlertsRoute
  '/trabajo/': typeof AuthenticatedTrabajoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pendiente': typeof PendienteRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/equipo': typeof AuthenticatedEquipoRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/huespedes': typeof AuthenticatedHuespedesRoute
  '/integraciones': typeof AuthenticatedIntegracionesRoute
  '/mis-tareas': typeof AuthenticatedMisTareasRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/propiedades': typeof AuthenticatedPropiedadesRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/control/dashboard': typeof ControlDashboardRoute
  '/control/empresas': typeof ControlEmpresasRoute
  '/control/licencias': typeof ControlLicenciasRoute
  '/control/sistema': typeof ControlSistemaRoute
  '/control/usuarios': typeof ControlUsuariosRoute
  '/invite/$token': typeof InviteTokenRoute
  '/control': typeof ControlIndexRoute
  '/trabajo/calendario': typeof AuthenticatedTrabajoCalendarioRoute
  '/trabajo/incidencias': typeof AuthenticatedTrabajoIncidenciasRoute
  '/trabajo/perfil': typeof AuthenticatedTrabajoPerfilRoute
  '/trabajo/tareas': typeof AuthenticatedTrabajoTareasRoute
  '/api/public/email-alerts': typeof ApiPublicEmailAlertsRoute
  '/trabajo': typeof AuthenticatedTrabajoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/control': typeof ControlRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pendiente': typeof PendienteRoute
  '/_authenticated/trabajo': typeof AuthenticatedTrabajoRouteRouteWithChildren
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/equipo': typeof AuthenticatedEquipoRoute
  '/_authenticated/finanzas': typeof AuthenticatedFinanzasRoute
  '/_authenticated/huespedes': typeof AuthenticatedHuespedesRoute
  '/_authenticated/integraciones': typeof AuthenticatedIntegracionesRoute
  '/_authenticated/mis-tareas': typeof AuthenticatedMisTareasRoute
  '/_authenticated/operaciones': typeof AuthenticatedOperacionesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/propiedades': typeof AuthenticatedPropiedadesRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/control/dashboard': typeof ControlDashboardRoute
  '/control/empresas': typeof ControlEmpresasRoute
  '/control/licencias': typeof ControlLicenciasRoute
  '/control/sistema': typeof ControlSistemaRoute
  '/control/usuarios': typeof ControlUsuariosRoute
  '/invite/$token': typeof InviteTokenRoute
  '/control/': typeof ControlIndexRoute
  '/_authenticated/trabajo/calendario': typeof AuthenticatedTrabajoCalendarioRoute
  '/_authenticated/trabajo/incidencias': typeof AuthenticatedTrabajoIncidenciasRoute
  '/_authenticated/trabajo/perfil': typeof AuthenticatedTrabajoPerfilRoute
  '/_authenticated/trabajo/tareas': typeof AuthenticatedTrabajoTareasRoute
  '/api/public/email-alerts': typeof ApiPublicEmailAlertsRoute
  '/_authenticated/trabajo/': typeof AuthenticatedTrabajoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/control'
    | '/auth'
    | '/pendiente'
    | '/trabajo'
    | '/alertas'
    | '/calendario'
    | '/configuracion'
    | '/equipo'
    | '/finanzas'
    | '/huespedes'
    | '/integraciones'
    | '/mis-tareas'
    | '/operaciones'
    | '/panel'
    | '/propiedades'
    | '/reportes'
    | '/reservas'
    | '/whatsapp'
    | '/control/dashboard'
    | '/control/empresas'
    | '/control/licencias'
    | '/control/sistema'
    | '/control/usuarios'
    | '/invite/$token'
    | '/control/'
    | '/trabajo/calendario'
    | '/trabajo/incidencias'
    | '/trabajo/perfil'
    | '/trabajo/tareas'
    | '/api/public/email-alerts'
    | '/trabajo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pendiente'
    | '/alertas'
    | '/calendario'
    | '/configuracion'
    | '/equipo'
    | '/finanzas'
    | '/huespedes'
    | '/integraciones'
    | '/mis-tareas'
    | '/operaciones'
    | '/panel'
    | '/propiedades'
    | '/reportes'
    | '/reservas'
    | '/whatsapp'
    | '/control/dashboard'
    | '/control/empresas'
    | '/control/licencias'
    | '/control/sistema'
    | '/control/usuarios'
    | '/invite/$token'
    | '/control'
    | '/trabajo/calendario'
    | '/trabajo/incidencias'
    | '/trabajo/perfil'
    | '/trabajo/tareas'
    | '/api/public/email-alerts'
    | '/trabajo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/control'
    | '/auth'
    | '/pendiente'
    | '/_authenticated/trabajo'
    | '/_authenticated/alertas'
    | '/_authenticated/calendario'
    | '/_authenticated/configuracion'
    | '/_authenticated/equipo'
    | '/_authenticated/finanzas'
    | '/_authenticated/huespedes'
    | '/_authenticated/integraciones'
    | '/_authenticated/mis-tareas'
    | '/_authenticated/operaciones'
    | '/_authenticated/panel'
    | '/_authenticated/propiedades'
    | '/_authenticated/reportes'
    | '/_authenticated/reservas'
    | '/_authenticated/whatsapp'
    | '/control/dashboard'
    | '/control/empresas'
    | '/control/licencias'
    | '/control/sistema'
    | '/control/usuarios'
    | '/invite/$token'
    | '/control/'
    | '/_authenticated/trabajo/calendario'
    | '/_authenticated/trabajo/incidencias'
    | '/_authenticated/trabajo/perfil'
    | '/_authenticated/trabajo/tareas'
    | '/api/public/email-alerts'
    | '/_authenticated/trabajo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ControlRouteRoute: typeof ControlRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PendienteRoute: typeof PendienteRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicEmailAlertsRoute: typeof ApiPublicEmailAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendiente': {
      id: '/pendiente'
      path: '/pendiente'
      fullPath: '/pendiente'
      preLoaderRoute: typeof PendienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipo': {
      id: '/_authenticated/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof AuthenticatedEquipoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finanzas': {
      id: '/_authenticated/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AuthenticatedFinanzasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/huespedes': {
      id: '/_authenticated/huespedes'
      path: '/huespedes'
      fullPath: '/huespedes'
      preLoaderRoute: typeof AuthenticatedHuespedesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integraciones': {
      id: '/_authenticated/integraciones'
      path: '/integraciones'
      fullPath: '/integraciones'
      preLoaderRoute: typeof AuthenticatedIntegracionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-tareas': {
      id: '/_authenticated/mis-tareas'
      path: '/mis-tareas'
      fullPath: '/mis-tareas'
      preLoaderRoute: typeof AuthenticatedMisTareasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operaciones': {
      id: '/_authenticated/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof AuthenticatedOperacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propiedades': {
      id: '/_authenticated/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof AuthenticatedPropiedadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trabajo': {
      id: '/_authenticated/trabajo'
      path: '/trabajo'
      fullPath: '/trabajo'
      preLoaderRoute: typeof AuthenticatedTrabajoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/control/': {
      id: '/control/'
      path: '/'
      fullPath: '/control/'
      preLoaderRoute: typeof ControlIndexRouteImport
      parentRoute: typeof ControlRouteRoute
    }
    '/control/dashboard': {
      id: '/control/dashboard'
      path: '/dashboard'
      fullPath: '/control/dashboard'
      preLoaderRoute: typeof ControlDashboardRouteImport
      parentRoute: typeof ControlRouteRoute
    }
    '/control/empresas': {
      id: '/control/empresas'
      path: '/empresas'
      fullPath: '/control/empresas'
      preLoaderRoute: typeof ControlEmpresasRouteImport
      parentRoute: typeof ControlRouteRoute
    }
    '/control/licencias': {
      id: '/control/licencias'
      path: '/licencias'
      fullPath: '/control/licencias'
      preLoaderRoute: typeof ControlLicenciasRouteImport
      parentRoute: typeof ControlRouteRoute
    }
    '/control/sistema': {
      id: '/control/sistema'
      path: '/sistema'
      fullPath: '/control/sistema'
      preLoaderRoute: typeof ControlSistemaRouteImport
      parentRoute: typeof ControlRouteRoute
    }
    '/control/usuarios': {
      id: '/control/usuarios'
      path: '/usuarios'
      fullPath: '/control/usuarios'
      preLoaderRoute: typeof ControlUsuariosRouteImport
      parentRoute: typeof ControlRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trabajo/': {
      id: '/_authenticated/trabajo/'
      path: '/'
      fullPath: '/trabajo/'
      preLoaderRoute: typeof AuthenticatedTrabajoIndexRouteImport
      parentRoute: typeof AuthenticatedTrabajoRouteRoute
    }
    '/_authenticated/trabajo/calendario': {
      id: '/_authenticated/trabajo/calendario'
      path: '/calendario'
      fullPath: '/trabajo/calendario'
      preLoaderRoute: typeof AuthenticatedTrabajoCalendarioRouteImport
      parentRoute: typeof AuthenticatedTrabajoRouteRoute
    }
    '/_authenticated/trabajo/incidencias': {
      id: '/_authenticated/trabajo/incidencias'
      path: '/incidencias'
      fullPath: '/trabajo/incidencias'
      preLoaderRoute: typeof AuthenticatedTrabajoIncidenciasRouteImport
      parentRoute: typeof AuthenticatedTrabajoRouteRoute
    }
    '/_authenticated/trabajo/perfil': {
      id: '/_authenticated/trabajo/perfil'
      path: '/perfil'
      fullPath: '/trabajo/perfil'
      preLoaderRoute: typeof AuthenticatedTrabajoPerfilRouteImport
      parentRoute: typeof AuthenticatedTrabajoRouteRoute
    }
    '/_authenticated/trabajo/tareas': {
      id: '/_authenticated/trabajo/tareas'
      path: '/tareas'
      fullPath: '/trabajo/tareas'
      preLoaderRoute: typeof AuthenticatedTrabajoTareasRouteImport
      parentRoute: typeof AuthenticatedTrabajoRouteRoute
    }
    '/api/public/email-alerts': {
      id: '/api/public/email-alerts'
      path: '/api/public/email-alerts'
      fullPath: '/api/public/email-alerts'
      preLoaderRoute: typeof ApiPublicEmailAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedTrabajoRouteRouteChildren {
  AuthenticatedTrabajoCalendarioRoute: typeof AuthenticatedTrabajoCalendarioRoute
  AuthenticatedTrabajoIncidenciasRoute: typeof AuthenticatedTrabajoIncidenciasRoute
  AuthenticatedTrabajoPerfilRoute: typeof AuthenticatedTrabajoPerfilRoute
  AuthenticatedTrabajoTareasRoute: typeof AuthenticatedTrabajoTareasRoute
  AuthenticatedTrabajoIndexRoute: typeof AuthenticatedTrabajoIndexRoute
}

const AuthenticatedTrabajoRouteRouteChildren: AuthenticatedTrabajoRouteRouteChildren =
  {
    AuthenticatedTrabajoCalendarioRoute: AuthenticatedTrabajoCalendarioRoute,
    AuthenticatedTrabajoIncidenciasRoute: AuthenticatedTrabajoIncidenciasRoute,
    AuthenticatedTrabajoPerfilRoute: AuthenticatedTrabajoPerfilRoute,
    AuthenticatedTrabajoTareasRoute: AuthenticatedTrabajoTareasRoute,
    AuthenticatedTrabajoIndexRoute: AuthenticatedTrabajoIndexRoute,
  }

const AuthenticatedTrabajoRouteRouteWithChildren =
  AuthenticatedTrabajoRouteRoute._addFileChildren(
    AuthenticatedTrabajoRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTrabajoRouteRoute: typeof AuthenticatedTrabajoRouteRouteWithChildren
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedEquipoRoute: typeof AuthenticatedEquipoRoute
  AuthenticatedFinanzasRoute: typeof AuthenticatedFinanzasRoute
  AuthenticatedHuespedesRoute: typeof AuthenticatedHuespedesRoute
  AuthenticatedIntegracionesRoute: typeof AuthenticatedIntegracionesRoute
  AuthenticatedMisTareasRoute: typeof AuthenticatedMisTareasRoute
  AuthenticatedOperacionesRoute: typeof AuthenticatedOperacionesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPropiedadesRoute: typeof AuthenticatedPropiedadesRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTrabajoRouteRoute: AuthenticatedTrabajoRouteRouteWithChildren,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedEquipoRoute: AuthenticatedEquipoRoute,
  AuthenticatedFinanzasRoute: AuthenticatedFinanzasRoute,
  AuthenticatedHuespedesRoute: AuthenticatedHuespedesRoute,
  AuthenticatedIntegracionesRoute: AuthenticatedIntegracionesRoute,
  AuthenticatedMisTareasRoute: AuthenticatedMisTareasRoute,
  AuthenticatedOperacionesRoute: AuthenticatedOperacionesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPropiedadesRoute: AuthenticatedPropiedadesRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ControlRouteRouteChildren {
  ControlDashboardRoute: typeof ControlDashboardRoute
  ControlEmpresasRoute: typeof ControlEmpresasRoute
  ControlLicenciasRoute: typeof ControlLicenciasRoute
  ControlSistemaRoute: typeof ControlSistemaRoute
  ControlUsuariosRoute: typeof ControlUsuariosRoute
  ControlIndexRoute: typeof ControlIndexRoute
}

const ControlRouteRouteChildren: ControlRouteRouteChildren = {
  ControlDashboardRoute: ControlDashboardRoute,
  ControlEmpresasRoute: ControlEmpresasRoute,
  ControlLicenciasRoute: ControlLicenciasRoute,
  ControlSistemaRoute: ControlSistemaRoute,
  ControlUsuariosRoute: ControlUsuariosRoute,
  ControlIndexRoute: ControlIndexRoute,
}

const ControlRouteRouteWithChildren = ControlRouteRoute._addFileChildren(
  ControlRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ControlRouteRoute: ControlRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PendienteRoute: PendienteRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicEmailAlertsRoute: ApiPublicEmailAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
