/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedFinanzasRouteImport } from './routes/_authenticated/finanzas'
import { Route as AuthenticatedHuespedesRouteImport } from './routes/_authenticated/huespedes'
import { Route as AuthenticatedOperacionesRouteImport } from './routes/_authenticated/operaciones'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedPropiedadesRouteImport } from './routes/_authenticated/propiedades'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanzasRoute = AuthenticatedFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHuespedesRoute = AuthenticatedHuespedesRouteImport.update({
  id: '/huespedes',
  path: '/huespedes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacionesRoute =
  AuthenticatedOperacionesRouteImport.update({
    id: '/operaciones',
    path: '/operaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropiedadesRoute =
  AuthenticatedPropiedadesRouteImport.update({
    id: '/propiedades',
    path: '/propiedades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/huespedes': typeof AuthenticatedHuespedesRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/propiedades': typeof AuthenticatedPropiedadesRoute
  '/reservas': typeof AuthenticatedReservasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/huespedes': typeof AuthenticatedHuespedesRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/propiedades': typeof AuthenticatedPropiedadesRoute
  '/reservas': typeof AuthenticatedReservasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/finanzas': typeof AuthenticatedFinanzasRoute
  '/_authenticated/huespedes': typeof AuthenticatedHuespedesRoute
  '/_authenticated/operaciones': typeof AuthenticatedOperacionesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/propiedades': typeof AuthenticatedPropiedadesRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendario'
    | '/finanzas'
    | '/huespedes'
    | '/operaciones'
    | '/panel'
    | '/propiedades'
    | '/reservas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendario'
    | '/finanzas'
    | '/huespedes'
    | '/operaciones'
    | '/panel'
    | '/propiedades'
    | '/reservas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calendario'
    | '/_authenticated/finanzas'
    | '/_authenticated/huespedes'
    | '/_authenticated/operaciones'
    | '/_authenticated/panel'
    | '/_authenticated/propiedades'
    | '/_authenticated/reservas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finanzas': {
      id: '/_authenticated/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AuthenticatedFinanzasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/huespedes': {
      id: '/_authenticated/huespedes'
      path: '/huespedes'
      fullPath: '/huespedes'
      preLoaderRoute: typeof AuthenticatedHuespedesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operaciones': {
      id: '/_authenticated/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof AuthenticatedOperacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propiedades': {
      id: '/_authenticated/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof AuthenticatedPropiedadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedFinanzasRoute: typeof AuthenticatedFinanzasRoute
  AuthenticatedHuespedesRoute: typeof AuthenticatedHuespedesRoute
  AuthenticatedOperacionesRoute: typeof AuthenticatedOperacionesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPropiedadesRoute: typeof AuthenticatedPropiedadesRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedFinanzasRoute: AuthenticatedFinanzasRoute,
  AuthenticatedHuespedesRoute: AuthenticatedHuespedesRoute,
  AuthenticatedOperacionesRoute: AuthenticatedOperacionesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPropiedadesRoute: AuthenticatedPropiedadesRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
